In [1]:
%pip install "ultralytics<=8.3.40" supervision roboflow

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import os
HOME = os.getcwd()

In [3]:
!yolo segment predict model=yolo11n-seg.pt source='https://media.roboflow.com/notebooks/examples/dog.jpeg' save=true

Ultralytics 8.3.27 🚀 Python-3.10.8 torch-2.5.1+cpu CPU (AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx)
YOLO11n-seg summary (fused): 265 layers, 2,868,664 parameters, 0 gradients, 10.4 GFLOPs

Found https://media.roboflow.com/notebooks/examples/dog.jpeg locally at dog.jpeg
image 1/1 c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\dog.jpeg: 640x384 1 person, 1 dog, 252.0ms
Speed: 0.0ms preprocess, 252.0ms inference, 11.8ms postprocess per image at shape (1, 3, 640, 384)
Results saved to runs\segment\predict
💡 Learn more at https://docs.ultralytics.com/modes/predict


In [4]:
!mkdir {HOME}/datasets
%cd {HOME}/datasets
                
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="BczLg7McXckd6Hn9L9Jb")
project = rf.workspace("masterproject-ragta").project("dark-field-detection")
version = project.version(1)
dataset = version.download("yolov11")
                
                

[WinError 2] Systemet finner ikke angitt fil: 'c:\\Users\\krist\\Documents\\masterRepo\\src\\testMaster\\YOLO11/datasets'
c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11


The syntax of the command is incorrect.
C:\Users\krist\AppData\Roaming\Python\Python310\site-packages\IPython\core\magics\osm.py:393: UserWarning: This is now an optional IPython functionality, using bookmarks requires you to install the `pickleshare` library.
  bkms = self.shell.db.get('bookmarks', {})


loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to Dark-Field-Detection-1 in yolov11:: 100%|██████████| 79/79 [00:00<00:00, 600.75it/s]


In [ ]:
%cd {HOME}

!yolo task=detect mode=train model=yolo11s.pt data={dataset.location}/data.yaml epochs=20 imgsz=1024 plots=True

c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11
^C


WARNING ⚠️ conflicting 'task=detect' passed with 'task=segment' model. Ignoring 'task=detect' and updating to 'task=segment' to match model.
New https://pypi.org/project/ultralytics/8.3.74 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.27 🚀 Python-3.10.8 torch-2.5.1+cpu CPU (AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx)
engine\trainer: task=segment, mode=train, model=yolo11s-seg.pt, data=c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\Dark-Field-Images--4/data.yaml, epochs=20, time=None, patience=100, batch=16, imgsz=1024, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=No


train: Scanning C:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\Dark-Field-Images--4\train\labels.cache... 15 images, 0 backgrounds, 0 corrupt: 100%|██████████| 15/15 [00:00<?, ?it/s]
train: Scanning C:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\Dark-Field-Images--4\train\labels.cache... 15 images, 0 backgrounds, 0 corrupt: 100%|██████████| 15/15 [00:00<?, ?it/s]

val: Scanning C:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\Dark-Field-Images--4\valid\labels.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]
val: Scanning C:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\Dark-Field-Images--4\valid\labels.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]


In [ ]:
project.version(dataset.version).deploy(model_type="yolov11", model_path=f"{HOME}/runs/detect/train/")

View the status of your deployment at: https://app.roboflow.com/masterproject-ragta/dark-field-images/1


In [6]:
print(result.masks.xy)

[array([[        244,         668],
       [        244,         674],
       [        242,         676],
       [        240,         676],
       [        238,         678],
       [        230,         678],
       [        228,         680],
       [        216,         680],
       [        214,         682],
       [        208,         682],
       [        204,         686],
       [        202,         686],
       [        190,         698],
       [        190,         700],
       [        188,         702],
       [        188,         704],
       [        180,         712],
       [        180,         714],
       [        176,         718],
       [        176,         722],
       [        174,         724],
       [        174,         726],
       [        172,         728],
       [        172,         730],
       [        170,         732],
       [        170,         734],
       [        168,         736],
       [        168,         738],
       [        166

In [6]:
result.boxes.xyxy

tensor([[0.0000e+00, 6.6554e+02, 4.4330e+02, 1.2796e+03],
        [7.1135e+01, 2.4946e+02, 6.4429e+02, 9.1890e+02],
        [1.1399e+00, 3.5346e+02, 6.1875e+02, 1.2769e+03],
        [6.2860e+02, 7.3525e+02, 6.9806e+02, 7.8718e+02]])

In [7]:
result.boxes.conf


tensor([0.9365, 0.9156, 0.8151, 0.7367])

In [8]:
result.boxes.cls

tensor([24., 16.,  0.,  2.])

In [9]:
result.masks.data

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 

In [13]:
!pip install roboflow


from roboflow import Roboflow
rf = Roboflow(api_key="BczLg7McXckd6Hn9L9Jb")
project = rf.workspace("masterproject-ragta").project("df-images-labelling")
version = project.version(1)
dataset = version.download("coco-segmentation")
                
                

loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to DF-Images-Labelling-1 in coco-segmentation:: 100%|██████████| 13/13 [00:00<00:00, 422.29it/s]


c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11\DF-Images-Labelling-1\data.yaml


In [16]:
%cd {HOME}

!yolo task=segment mode=train model=yolo11s-seg.pt data="C:/Users/krist/Documents/masterRepo/src/testMaster/YOLO11/DF-Images-Labelling-1" epochs=10 imgsz=2048 plots=True


c:\Users\krist\Documents\masterRepo\src\testMaster\YOLO11
New https://pypi.org/project/ultralytics/8.3.70 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.27 🚀 Python-3.10.8 torch-2.5.1+cpu CPU (AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx)
engine\trainer: task=segment, mode=train, model=yolo11s-seg.pt, data=C:/Users/krist/Documents/masterRepo/src/testMaster/YOLO11/DF-Images-Labelling-1, epochs=10, time=None, patience=100, batch=16, imgsz=2048, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, strea

Traceback (most recent call last):
  File "C:\Users\krist\AppData\Roaming\Python\Python310\site-packages\ultralytics\engine\trainer.py", line 557, in get_dataset
    data = check_det_dataset(self.args.data)
  File "C:\Users\krist\AppData\Roaming\Python\Python310\site-packages\ultralytics\data\utils.py", line 273, in check_det_dataset
    if zipfile.is_zipfile(file) or is_tarfile(file):
  File "c:\Users\krist\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 2517, in is_tarfile
    t = open(name)
  File "c:\Users\krist\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "c:\Users\krist\AppData\Local\Programs\Python\Python310\lib\tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "c:\Users\krist\AppData\Local\Programs\Python\Python310\lib\gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
Permissi

In [34]:
project.version(dataset.version).deploy(model_type="yolov11", model_path=f"{HOME}/runs/segment/train6/")

View the status of your deployment at: https://app.roboflow.com/masterproject-ragta/dark-field-images/2
Share your model with the world at: https://universe.roboflow.com/masterproject-ragta/dark-field-images/model/2


In [6]:
from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/segment/train/confusion_matrix.png', width=600)

FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\krist\\Documents\\masterRepo\\src\\testMaster\\YOLO11/runs/segment/train/confusion_matrix.png'

In [ ]:
from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/segment/train/results.png', width=600)

In [ ]:
from IPython.display import Image as IPyImage

IPyImage(filename=f'{HOME}/runs/segment/train/val_batch0_pred.jpg', width=600)

In [ ]:
!yolo task=detect mode=val model={HOME}/runs/segment/train/weights/best.pt data={dataset.location}/data.yaml


In [ ]:
!yolo task=detect mode=predict model={HOME}/runs/segment/train/weights/best.pt conf=0.25 source={dataset.location}/test/images save=True


In [1]:
import glob
import os
from IPython.display import Image as IPyImage, display

latest_folder = max(glob.glob(f'{HOME}/runs/segment/predict*/'), key=os.path.getmtime)
for img in glob.glob(f'{latest_folder}/*.jpg')[:3]:
    display(IPyImage(filename=img, width=600))
    print("\n")

NameError: name 'HOME' is not defined

  Using cached pycocotools-2.0.8-cp310-cp310-win_amd64.whl.metadata (1.1 kB)
Using cached pycocotools-2.0.8-cp310-cp310-win_amd64.whl (84 kB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 1.4/1.4 MB 12.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
%pip install roifile



Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [23]:
import numpy as np
import json
from roifile import ImagejRoi

# Load ROIs from a ZIP file
rois = ImagejRoi.fromfile("test.zip")

# Define dataset metadata
info = {
    "year": "2024",
    "version": "1",
    "description": "Exported from ROI files",
    "contributor": "",
    "url": "",
    "date_created": "2024-06-05T10:15:36+00:00"
}

# Define license info
licenses = [
    {
        "id": 1,
        "url": "https://creativecommons.org/publicdomain/zero/1.0/",
        "name": "Public Domain"
    }
]

# Define categories (single category: cross_sections)
categories = [
    {
        "id": 0,
        "name": "cross_sections",
        "supercategory": "none"
    }
]

# Define image metadata
image_metadata = {
    "id": 0,
    "license": 1,
    "file_name": "ye.jpg",  # Ensure it matches the actual image file name
    "height": 2048,  # Change to actual image height
    "width": 2048,   # Change to actual image width
    "date_captured": "2024-06-05T10:15:36+00:00"
}

# Convert ROIs to COCO-style format
annotations = [
    {
        "id": idx,
        "image_id": 0,
        "category_id": 0,
        "bbox": [
            min(coord[0] + roi.left for coord in roi.coordinates().tolist()),
            min(coord[1] + roi.top for coord in roi.coordinates().tolist()),
            roi.right - roi.left,
            roi.bottom - roi.top
        ],
        "area": (roi.right - roi.left) * (roi.bottom - roi.top),
        "segmentation": [coord for point in roi.coordinates().tolist() for coord in (point[0] + roi.left, point[1] + roi.top)],
        "iscrowd": 0
    }
    for idx, roi in enumerate(rois)
]

# Create COCO annotation dictionary
coco_annotation = {
    "info": info,
    "licenses": licenses,
    "categories": categories,
    "images": [image_metadata],
    "annotations": annotations
}

# Save annotations to a JSON file
with open("test.json", "w") as f:
    json.dump(coco_annotation, f, indent=2)
